apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 172.18.204.200-172.18.204.207
  autoAssign: true
  avoidBuggyIPs: false  
